name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: sbt
        
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
          
    - name: Check formatting, compile, test with coverage
      run: sbt releaseLocal

