name: "Publish Release Artifacts"
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  publish-release:
    runs-on: "codebuild-ion-spark-data-source-${{ github.run_id }}-${{ github.run_attempt }}"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3.6.0
        with:
          submodule: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: sbt
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Publish
        run: sbt ci-release
